USE ESTUDO
GO

-- Verify that the stored procedure does not already exist.
IF OBJECT_ID('usp_GetErrorInfo', 'P') IS NOT NULL
	DROP PROCEDURE usp_GetErrorInfo;
GO

-- Create procedure to retrieve error information.
CREATE PROCEDURE usp_GetErrorInfo
AS
BEGIN
	DECLARE @ERRORNUMBER INT
	DECLARE @ERROREVERITY INT
	DECLARE @ERRORSTATE INT
	DECLARE @ERRORPROCEDURE VARCHAR(40)
	DECLARE @ERRORLINE INT
	DECLARE @ERRORMESSAGE VARCHAR(40)
	DECLARE @DATA DATETIME

	SET @ERRORNUMBER = ERROR_NUMBER()
	SET @ERROREVERITY = ERROR_SEVERITY()
	SET @ERRORSTATE = ERROR_STATE()
	SET @ERRORPROCEDURE = ERROR_PROCEDURE()
	SET @ERRORLINE = ERROR_LINE()
	SET @ERRORMESSAGE = ERROR_MESSAGE()
	SET @DATA = GETDATE()

	BEGIN TRY
		INSERT INTO [dbo].[LOGERRO] (
			[IDLOGERRO]
			,[ERRORNUMBER]
			,[ERRORSTATE]
			,[ERRORPROCEDURE]
			,[ERRORLINE]
			,[ERRORMESSAGE]
			,[DATA]
			,[ERROREVERITY]
			)
		VALUES (
			SUBSTRING(CONVERT(VARCHAR, RAND()), 3, 9)
			,@ERRORNUMBER
			,@ERRORSTATE
			,@ERRORPROCEDURE
			,@ERRORLINE
			,@ERRORMESSAGE
			,@DATA
			,@ERROREVERITY
			)
	END TRY

	BEGIN CATCH
		PRINT 'Erro de gravação de log de erro. Stored Procedure - usp_GetErrorInfo. '
	END CATCH
END
GO

--BEGIN TRY
---- Generate divide-by-zero error.
--SELECT 1 / 0;
--END TRY
--BEGIN CATCH
---- Execute error retrieval routine.
--EXECUTE usp_GetErrorInfo;
--SELECT *  FROM LOGERRO
--END CATCH;

