--SELECT *
--FROM SE4010 SE4
--WHERE SE4.D_E_L_E_T_= ''
--AND SE4.E4_CODIGO = '008'


SELECT A1_CGC	AS 'CNPJ',
A1_COD AS 'CODIGO',
A1_NOME AS 'RAZÃO SOCIAL',  
A1_NREDUZ AS 'NOME FANTASIA' ,         
A1_COND AS 'COD. CONDIÇÃO PAG', 
	E4_TIPO AS 'TIPO CONDIÇÃO',	
	E4_COND AS 'CONDIÇÃO DE PAG',	
	E4_DESCRI AS 'DESCRIÇÃO',	
	E4_IPI AS 'IPI',	
	E4_DDD AS 'DIAS DA CONDIÇÃO',	
	E4_DESCFIN AS 'DESCONTO FINANCEIRO',	
	E4_DIADESC AS 'DIAS P/ DESC FINANCEIRO',	
	E4_FORMA AS 'FORMA DE PAGAMENTO',	
	E4_ACRSFIN AS '%ACRESCIMO FINANCEIRO',	
	E4_SOLID AS 'ICMS SOLIDARIO', 	
	E4_PERCOM AS 'PERCENTUAL DE COMISSÃO',	
	E4_SUPER AS 'LIMITE DE VENDA SUPERIOR',	
	E4_INFER AS 'LIMETE DE VENDA INFERIOR',	
	E4_FATOR AS 'FATOR PARA MULTIPLICAÇÃO DO VALOR FINAN-CIADO EM UMA VENDA.',	
	E4_JURCART AS 'JUROS DO CARTÃO POR CONTA',	
	E4_PLANO AS 'PLANO INFOCARD',	
	E4_ACRES AS 'ACRESCIMO FINANCEIRO',	
	E4_ZFLAG AS 'INTEGRAÇÃO SISPLAN',	
	E4_CTRADT AS 'PERMITE ADIANTAMENTO?',	
	E4_AGRACRS AS 'AGREGA ACRS.',	
	E4_LIMACRS AS 'Limite dias Pagamento',	
	E4_CCORREN AS 'Conta COrrente',		
	E4_MSBLQL AS 'Status do registro'
FROM SA1010 SA1 
INNER JOIN SE4010 SE4
ON  SE4.D_E_L_E_T_= ''
AND SE4.E4_CODIGO = A1_COND
WHERE SA1.D_E_L_E_T_ = ''
AND E4_ZFLAG = 'T'